[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "ecompayments-python-sdk"
version = "0.1.0"
description = "Python SDK for Ecom Payments"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]
authors = [{ name = "Ecom Payments" }]
keywords = ["ecom", "payments", "sdk", "eapi", "elinks"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Typing :: Typed"
]
dependencies = []

[project.urls]
Documentation = "https://ecom-payments-developer-api.readme.io"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
ecom_payments = ["py.typed"]
[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]
branch = "main"
